add field and seed info
ssharba/sftp_scheduler pull request #2
Opened 2017-12-05 19:14 UTC by louy755

2017-12-05 19:18 UTC, ssharba requested changes

2017-12-05 19:18 UTC, ssharba commented on db/seeds.rb
> +ClientFile.destroy_all
can we use smarter way to seed data? create a hash of data and loop through it.

2017-12-05 19:21 UTC, louy755 commented on db/seeds.rb
> +ClientFile.destroy_all
so just remove this line or create a hash  of date ?

2017-12-05 19:46 UTC, ssharba commented on db/seeds.rb
> +ClientFile.destroy_all
create a loop to create your objects

2017-12-05 20:39 UTC, ssharba commented on db/seeds.rb
> +
@louy755 create client and client_files in one loop.

2017-12-05 20:40 UTC, ssharba commented on db/seeds.rb
> +  { file_format: "ali_lol_12052017.txt", regex: "DHP_Grp", client_id: 1 },
where did you get this file name? please check the card.

2017-12-05 21:44 UTC, louy755 commented on db/seeds.rb
> +  { file_format: "ali_lol_12052017.txt", regex: "DHP_Grp", client_id: 1 },
proceeding!

2017-12-05 21:44 UTC, louy755 commented on db/seeds.rb
> +
proceeding!

2017-12-06 16:43 UTC, ssharba requested changes

2017-12-06 16:43 UTC, ssharba commented on db/seeds.rb
> +client_hashes = [
one nested loop only please

2017-12-06 20:38 UTC, ssharba commented on db/seeds.rb
> +ClientFile.delete_all
can we add something to the client model that will delete all client_files when we delete client?

2017-12-06 20:53 UTC, louy755 commented on db/seeds.rb
> +ClientFile.delete_all
sure!

2017-12-06 20:56 UTC, ssharba approved these changes

2017-12-06 20:56 UTC, merged