add job download
ssharba/sftp_scheduler pull request #4
Opened 2017-12-11 19:00 UTC by louy755

2017-12-11 20:24 UTC, Azzawie requested changes

2017-12-11 20:24 UTC, MwMaki commented on app/models/client.rb
> +    DownloadJob.perform_async(id)
@louy755 is this method working without defining self ? where do you call it?

2017-12-11 20:24 UTC, MwMaki commented on app/jobs/download_job.rb
> +     600
this will not work as long as it's explicit value

2017-12-11 20:24 UTC, MwMaki commented on app/jobs/download_job.rb
> +    Net::SSH.start("test.rebex.net", "demo", password: ("password")) do |ssh|
instead of using ssh and entering 3 loops  (net-ssh,ssh-sftp,client_file), it's better to use    Net::SFTP.start()   directly  so you will have 2 loops( sftp, client_files ),

2017-12-11 20:24 UTC, MwMaki commented on app/jobs/download_job.rb
> +          Dir.mkdir "#{Rails.root}/public/#{client.name}/" unless Dir.exists? "#{Rails.root}/public/#{client.name}"
Take the folder creation out of the files loop so you will create it once and no need for the unless condition

2017-12-11 20:24 UTC, MwMaki commented on app/jobs/download_job.rb
> +          file_name = file.file_format
how come file name = file format ?

2017-12-11 20:24 UTC, MwMaki commented on app/jobs/download_job.rb
> +          sftp.download! "/pub/example/#{file_name}", "#{Rails.root}/public/#{client.name}/#{file_name}"
to make thing more clear & easier  you can assign (#{Rails.root}/public/#{client.name}/) to a variable and use that variable instead of keep repeat long line

2017-12-11 20:45 UTC, ssharba requested changes

2017-12-11 20:45 UTC, ssharba commented on app/jobs/download_job.rb
> +     600
I think we can override sidekiq confirmations to achieve this, what do you think @MwMaki ?

2017-12-11 20:45 UTC, ssharba commented on app/jobs/download_job.rb
> +    Net::SSH.start("test.rebex.net", "demo", password: ("password")) do |ssh|
agree!

2017-12-11 20:45 UTC, ssharba commented on app/jobs/download_job.rb
> +    Net::SSH.start("test.rebex.net", "demo", password: ("password")) do |ssh|
Also, I would move all logic to a helper method and just call it in the job.

2017-12-11 20:45 UTC, ssharba commented on app/jobs/download_job.rb
> +          file_name = file.file_format
@MwMaki because we saved the file name in this field, it's okey don't change it.

2017-12-11 20:49 UTC, MwMaki commented on app/jobs/download_job.rb
> +     600
@ssharba yes indeed ,we can use this way to control the delay

2017-12-11 21:41 UTC, louy755 commented on app/jobs/download_job.rb
> +     600
This one is work and tested you can check on (https://github.com/mperham/sidekiq/wiki/Error-Handling)

2017-12-11 21:43 UTC, louy755 commented on app/jobs/download_job.rb
> +    Net::SSH.start("test.rebex.net", "demo", password: ("password")) do |ssh|
I think you mean blocks here, not loops

2017-12-11 21:48 UTC, Azzawie requested changes

2017-12-11 21:48 UTC, MwMaki commented on app/jobs/download_job.rb
> +     600
@louy755  No need to copy and past the website link as long as I memorize it ,compare your code to the one in the website and see what i mean

2017-12-11 21:48 UTC, MwMaki commented on app/jobs/download_job.rb
> +    Net::SSH.start("test.rebex.net", "demo", password: ("password")) do |ssh|
loops

2017-12-11 22:19 UTC, ssharba requested changes

2017-12-11 22:19 UTC, ssharba commented on app/models/client.rb
> +    DownloadJob.perform_async(id)
I didn't ask for this method

2017-12-11 22:19 UTC, ssharba commented on app/jobs/download_job.rb
> +    client = Client.find(client_id)
move all logic out of the job PLEASE.

2017-12-11 22:19 UTC, ssharba commented on app/jobs/download_job.rb
> +      download_file(file_name, client_name)
what id if the file not there?

2017-12-11 22:19 UTC, ssharba commented on app/jobs/download_job.rb
> +  def download_file(file_name, client_name)
this method must go out of the active job, but it in the library and call it.

2017-12-11 22:19 UTC, ssharba commented on app/jobs/download_job.rb
> +  sidekiq_retry_in do |count|
see if we can have this values in sidekiq configuration, so it will be easy to change.

2017-12-12 00:32 UTC, louy755 commented on app/jobs/download_job.rb
> +      download_file(file_name, client_name)
We will retry every 10 mins for 10 attempts. And then we will log the message

2017-12-12 23:25 UTC, ssharba requested changes

2017-12-12 23:25 UTC, ssharba commented on app/jobs/download_job.rb
> +      Net::SFTP.start("test.rebex.net", "demo", password: ("password")) do |sftp|
move this part to a method
Net::SFTP.start("test.rebex.net", "demo", password: ("password")) do |sftp|
   sftp.download! "/pub/example/#{file_name}", file_path
end

2017-12-12 23:25 UTC, ssharba commented on lib/sftp_download.rb
> +  def self.process_file_for_download(client_id)
create a job that will take client_id as an arrangement!!!

2017-12-12 23:25 UTC, ssharba commented on app/jobs/download_job.rb
> +  sidekiq_retry_in do |count|
?

2017-12-13 18:03 UTC, louy755 commented on app/jobs/download_job.rb
> +  sidekiq_retry_in do |count|
this is the time of each retry!

2017-12-13 18:03 UTC, louy755 commented on app/jobs/download_job.rb
> +    client = Client.find(client_id)
sure!

2017-12-13 18:04 UTC, louy755 commented on app/jobs/download_job.rb
> +      Net::SFTP.start("test.rebex.net", "demo", password: ("password")) do |sftp|
proceeding to move this part to the lib folder.

2017-12-13 18:13 UTC, ssharba commented on app/jobs/download_job.rb
> +  sidekiq_retry_in do |count|
I know what it does, I'm asking if you can move it to the sidekiq config file.

2017-12-13 20:12 UTC, louy755 commented on app/jobs/download_job.rb
> +  sidekiq_retry_in do |count|
I couldn't find the configuration option for it. I think the sidekiq config file is only for options that you can pass to the command line while starting up sidekiq.

2017-12-13 20:30 UTC, merged