Nt aws download upload methods
ssharba/sftp_scheduler pull request #5
Opened 2017-12-13 18:03 UTC by nooralnabi

2017-12-14 02:53 UTC, ssharba commented
conflicts

2017-12-14 04:04 UTC, Azzawie requested changes

2017-12-14 04:04 UTC, MwMaki commented on lib/helper_methods.rb
> +           Dir["#{files_dir}*.zip"].select.each do |file|
we don't need to loop on the folder as we will receive one zip file to extract

2017-12-14 04:04 UTC, MwMaki commented on lib/helper_methods.rb
> +           unzip_file(files_dir)
send only the file path to the unzip method instead of folder

2017-12-14 04:04 UTC, MwMaki commented on lib/helper_methods.rb
> +                  entry.extract(file_path)
after extracting all zip files  we should have  one file which is 100 g in our case

2017-12-14 04:04 UTC, MwMaki commented on app/controllers/api/v1/client_controller.rb
> +  HelperMethods.aws_upload(files_dir)
after receiving and extract the 10 parts of the file  ,only then  you will upload it as one file  so the upload should be in different action

2017-12-14 07:23 UTC, nooralnabi commented on lib/helper_methods.rb
> +                  entry.extract(file_path)
@MwMaki yes after download all part of file

2017-12-14 16:51 UTC, Azzawie requested changes

2017-12-14 16:51 UTC, MwMaki commented on lib/helper_methods.rb
> +          file = Dir.glob("#{files_dir}*.zip").first
@nooralnabi what if you have old zip files ?? it will give you the 1st one always not the newest one , I asked to to pass the zip file path  so you target the correct file

2017-12-14 16:53 UTC, Azzawie requested changes

2017-12-14 16:53 UTC, MwMaki commented on app/controllers/api/v1/client_controller.rb
> +  def upload_to_aws
you need to pass argument with the action call !

2017-12-14 18:30 UTC, Azzawie requested changes

2017-12-14 18:30 UTC, MwMaki commented on lib/helper_methods.rb
> +          file = Dir.glob("#{files_dir}").first
de we need this line any more ?

2017-12-14 18:50 UTC, nooralnabi commented on lib/helper_methods.rb
> +          file = Dir.glob("#{files_dir}").first
yes to convert path from  array to string,  because Dir method return an array

2017-12-14 19:12 UTC, MwMaki commented on lib/helper_methods.rb
> +          file = Dir.glob("#{files_dir}").first
Why we have array? We sent only one file path right?

2017-12-15 19:09 UTC, ssharba approved these changes

2017-12-15 19:09 UTC, merged