Env lookup
ssharba/sftp_scheduler pull request #6
Opened 2017-12-14 18:50 UTC by louy755

2017-12-14 20:39 UTC, ssharba commented on config/initializers/client_environment.rb
> +  $ENVIRONMENTS = YAML.load_file("#{Rails.root}/config/client.yml")
what is the structure of this yml file. can you share it here

2017-12-14 21:30 UTC, louy755 reviewed
@samer the config/client.yml??

2017-12-14 21:30 UTC, louy755 commented on config/initializers/client_environment.rb
> +  $ENVIRONMENTS = YAML.load_file("#{Rails.root}/config/client.yml")
@samer the config/client.yml!

2017-12-15 01:38 UTC, ssharba commented on config/initializers/client_environment.rb
> +  $ENVIRONMENTS = YAML.load_file("#{Rails.root}/config/client.yml")
- :name: Environment_1
  :env_id: 1
  :database_name: DB1
  :clients:
    - :id: 1
      :name: client_1
    - :id: 2
      :name: client_2
    - :id: 3
      :name: client_3
- :name: Environment_2
  :env_id: 2
  :database_name: DB2
  :clients:
    - :id: 4
      :name: client_4
    - :id: 5
      :name: client_3

2017-12-15 02:29 UTC, louy755 commented on config/initializers/client_environment.rb
> +  $ENVIRONMENTS = YAML.load_file("#{Rails.root}/config/client.yml")
proceeding!

2017-12-15 16:58 UTC, ssharba requested changes

2017-12-15 16:58 UTC, ssharba commented on lib/find_environment.rb
> +      environment = $ENVIRONMENTS.detect do |client_environment|
let's use find instead of detect.

2017-12-15 17:00 UTC, ssharba commented on lib/find_environment.rb
> +      environment = $ENVIRONMENTS.detect do |client_environment|
@MwMaki use this method in the logger please.

2017-12-15 17:01 UTC, louy755 commented on lib/find_environment.rb
> +      environment = $ENVIRONMENTS.detect do |client_environment|
Sure!

2017-12-15 17:03 UTC, ssharba approved these changes

2017-12-15 17:03 UTC, merged